At this moment, you face a grave problem. Your daughter has contracted a strange disease, and none of your home remedies seem to have any effect.
You've recently scraped all your gold together to pay a specialist doctor from beyond the mountains, but it appears like even he's at his wits' end.

You sense that your daughter is in mortal danger, and you must try to save her. One option you have is to undertake a journey into the caverns of Larn, which are generally thought to be magnificent in design, and contain much magic and treasure.

It has been said that there once was a great magician who called himself Polinneaus. Many years ago, after having had many miraculous successes, he retired to these very caverns, where he devoted most of his time to the creation of magic. Though he supposedly died many years ago, you might be able to gather enough money there to cover further medical expenses and perhaps even find something that might help your daughter.

    Good Luck!  You're going to need it!
