name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        c_compiler: [gcc, clang]
        configuration:
          - config=debug
          - config=release
          - config=debug SETGID=Y
          - config=release SETGID=Y
          - config=debug SDLPDCURSES=Y
          - config=release SDLPDCURSES=Y

    steps:
    - uses: actions/checkout@v4
    - name: Update apt cache
      run: sudo apt update
    - name: Install dependencies
      run: sudo apt install libglib2.0-dev pandoc
    - name: Install PDCurses dependencies
      run: sudo apt install libsdl2-dev libsdl2-ttf-dev
      if: contains(matrix.configuration, 'SDLPDCURSES=Y')
    - name: Build ${{ matrix.configuration }}
      run: make ${{ matrix.configuration }}

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - config=debug
          - config=release
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install pandoc
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install pandoc
    - uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        msystem: UCRT64
        update: true
        install: >
          git
          make
          zip
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-glib2
          mingw-w64-ucrt-x86_64-ncurses
          mingw-w64-ucrt-x86_64-nsis
          mingw-w64-ucrt-x86_64-pkg-config
          mingw-w64-ucrt-x86_64-SDL2
          mingw-w64-ucrt-x86_64-SDL2_ttf
          mingw-w64-ucrt-x86_64-zlib
    - uses: actions/checkout@v4
    - name: Build ${{ matrix.configuration }}
      run: make SDLPDCURSES=Y ${{ matrix.configuration }}

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration:
# FIXME: building with ncurses is broken
#          - config=debug
#          - config=release
          - config=debug SDLPDCURSES=Y
          - config=release SDLPDCURSES=Y
    env:
      PKG_CONFIG_PATH: /opt/homebrew/opt/ncurses/lib/pkgconfig
    steps:
    - uses: actions/checkout@v4
    - name: Update brew cache
      run: brew update
    - name: Install dependencies
      run: brew install dylibbundler glib ncurses pandoc pkg-config sdl2 sdl2_ttf
    - name: Build ${{ matrix.configuration }}
      run: make ${{ matrix.configuration }}
